documents:
- name: settings
  parser: tests.sublime_settings_parser
  options:
    group_comments: true
  sources:
  - '.'
  aspell:
    lang: en
  dictionary:
    lang: en
    wordlists:
    - docs/src/dictionary/en-custom.txt
    output: build/dictionary/settings.dic
  filters:
  - pyspelling.filters.context_filter:
      context_visible_first: true
      escapes: \\[\\`~]
      delimiters:
      - open: (?P<open>`+)
        content: .*?
        close: (?P=open)
      - open: (?s)^(?P<open>\s*~{3,})
        content: .*?
        close: ^(?P=open)$

- name: mkdocs
  parser: pyspelling.parsers.html_parser
  options:
    comments: false
    attributes:
    - title
    - alt
    ignores:
    - code
    - pre
    - a.magiclink-compare
    - a.magiclink-commit
    - span.keys
    - .MathJax_Preview
    - .md-nav__link
    - .md-footer-custom-text
    - .md-source__repository
    - .headerlink
    - .md-icon
  sources:
  - site
  aspell:
    lang: en
  dictionary:
    lang: en
    wordlists:
    - docs/src/dictionary/en-custom.txt
    output: build/dictionary/mkdocs.dic

- name: markdown
  parser: pyspelling.parsers.markdown_parser
  sources:
  - readme.md
  aspell:
    lang: en
  dictionary:
    lang: en
    wordlists:
    - docs/src/dictionary/en-custom.txt
    output: build/dictionary/markdown.dic
  filters:
  - pyspelling.filters.html_filter:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre

- name: python
  parser: pyspelling.parsers.python_parser
  options:
    comments: false
    strings: false
  sources:
  - '.'
  aspell:
    lang: en
  dictionary:
    lang: en
    wordlists:
    - docs/src/dictionary/en-custom.txt
    output: build/dictionary/python.dic
  filters:
  - pyspelling.filters.context_filter:
      context_visible_first: true
      escapes: \\[\\`~]
      delimiters:
      - open: (?P<open>`+)
        content: .*?
        close: (?P=open)
      - open: (?s)^(?P<open>\s*~{3,})
        content: .*?
        close: ^(?P=open)$
